[package]
name = "proto-sim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arbiter = { path = "../arbiter-fork" }
bindings = {path = "out/bindings"}
m3-rs = { path ="../af-rs" }
