name: Cargo Build & Test

on:
  push:
  pull_request:

env: 
  CARGO_TERM_COLOR: always

jobs:
  install_compile:
    name: Foundry install and compile
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run build script
      run: |
         chmod +x ./build.sh
         ./build.sh
      shell: bash
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build --verbose
      - run: cargo test --verbose